repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.2
    hooks:
      - id: uv-lock

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.7
  hooks:
    - id: ruff
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
