[project]
name = "gpu-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic",
    "python-fasthtml"
]

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
